# Generated by Django 3.2.8 on 2021-11-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
