# Generated by Django 3.2.8 on 2021-12-01 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20211129_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 1, 20, 19, 11, 350082, tzinfo=utc)),
        ),
    ]
