# Generated by Django 3.2.8 on 2021-12-11 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20211211_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='county',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='contact',
            name='datetime',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 12, 11, 12, 32, 36, 168352, tzinfo=utc)),
        ),
    ]
